### ISSUE TITLE
When I run python telegram.py. It's ERROR

### ISSUE THREAD

**Issue by haind13** [GabrielRF/Zabbix-Telegram-Notification#2]
I run python telegram.py, it is ERROR

> Traceback (most recent call last):
>   File "telegram.py", line 6, in <module>
>     DESTINATION=sys.argv[1]
> IndexError: list index out of range

How to fix it?

**Comment by GabrielRF** [comment]
You need to run `telegram.py` with three parameters.

**Comment by GabrielRF** [comment]
@haind13 Did it work?
