### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by impassenet** [GabrielRF/Zabbix-Telegram-Notification#3]
I follow your Readme but have an error with python script

**Traceback (most recent call last):
File "/usr/src/zabbixbot//telegram_notification.py", line 6, in <module>
DESTINATION=sys.argv[1]
IndexError: list index out of range**

**Comment by zhang12c** [comment]
我也遇到你和你一样的问题

**Comment by zhang12c** [comment]
impassenet你好，我的问题已经解决了，你需要在动作中设置3个参数。
Actions
Open Zabbix web interface, go to Configuration, Actions and click on Create Action.

Name: Telegram notification
Subject: #{HOSTNAME}: {TRIGGER.NAME} {TRIGGER.STATUS}
Message:

**Comment by GabrielRF** [comment]
@impassenet Could you fix it? 
If not, call me on Telegram. @GabrielRF
